// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNg-R2IfwY3x6i2EzDkqkJwK7z1HU4vwI',
    appId: '1:48844072795:web:a4ea86f8e645418dc59c7e',
    messagingSenderId: '48844072795',
    projectId: 'final-project-c5630',
    authDomain: 'final-project-c5630.firebaseapp.com',
    storageBucket: 'final-project-c5630.appspot.com',
    measurementId: 'G-BW4VLTJ55G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfH_oLUCv7N4qncCY6_Izm82ZeKiGYTFg',
    appId: '1:48844072795:android:756193301bc64aaec59c7e',
    messagingSenderId: '48844072795',
    projectId: 'final-project-c5630',
    storageBucket: 'final-project-c5630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoSkaAFApxhSCL5RmdKKDU0g9CbB8eeUw',
    appId: '1:48844072795:ios:8ad84b81ef219d9cc59c7e',
    messagingSenderId: '48844072795',
    projectId: 'final-project-c5630',
    storageBucket: 'final-project-c5630.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoSkaAFApxhSCL5RmdKKDU0g9CbB8eeUw',
    appId: '1:48844072795:ios:8ad84b81ef219d9cc59c7e',
    messagingSenderId: '48844072795',
    projectId: 'final-project-c5630',
    storageBucket: 'final-project-c5630.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNg-R2IfwY3x6i2EzDkqkJwK7z1HU4vwI',
    appId: '1:48844072795:web:88cb642ebf384c46c59c7e',
    messagingSenderId: '48844072795',
    projectId: 'final-project-c5630',
    authDomain: 'final-project-c5630.firebaseapp.com',
    storageBucket: 'final-project-c5630.appspot.com',
    measurementId: 'G-KDS4FMJM35',
  );
}
